import fs from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {build} from 'vite';
import {categorySlug} from '../src/catalogue.mjs';
import React from 'react';
import {renderToString} from 'react-dom/server';
const baseArg=process.argv.find(a=>a.startsWith('--base='));
const base=baseArg?baseArg.slice(7):'/';
const site='https://s0hamkadam13012005.github.io/nidhi-cosmetics/';
const products=JSON.parse(await fs.readFile('src/data/products.json','utf8'));
const categories=JSON.parse(await fs.readFile('src/data/categories.json','utf8'));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slug=categorySlug;
const categoryCopy={"Bath & Body":"Explore EYLIN shower gels, body lotions, body milk and talcum powder across botanical and spa collections. Browse individual products and coordinate them with your guest amenity kits.","Hair Care":"Browse EYLIN shampoos and hair conditioner, including Moringa, Neem & Aloe Vera, Onion & Amla and Spa Absolute Jasmin. Enquire about available pack sizes and hospitality supply.","Soaps":"Discover EYLIN and Zivara guest soaps, from Fuji Green Tea and Bulgarian Rose to Oud and wrapped guest-room bars. View photographs and enquire about sizes and packaging.","Gift Sets":"Browse 14 coordinated EYLIN guest amenity collections. Explore the individual soaps, shampoos and body-care products in each range and choose your preferred kit contents.","Handwash":"Explore Zivara handwash in Aqua Blue, Strawberry, Neem & Aloe Vera, Eco, and Aloe Vera & Lemongrass. View the supplied 5-litre packs and enquire about order quantities.","Dry Amenities":"Find dental kits, shaving kits, combs, shower caps, sewing kits and guest-room accessories. Explore amenity boxes, paper pouches and presentation options for your property.","Slippers":"Browse hotel guest slippers in jute, white open-toe, white closed-toe and black styles. Enquire about available sizes, materials and quantities for your property.","Dispensers":"Explore single and double amenity dispensers in metal and plastic options. View product photographs and discuss suitable packaging for your bathroom amenities.","Cleaning Products":"Browse Zivara housekeeping and cleaning products for property operations. Review each product and enquire about available packs, specifications and order quantities.","Air Fresheners":"Discover six Zivara air fresheners: Bulgarian Rose, Evening Paris, Lavender, Lemongrass, London Dreams and Sandal. View the 5-litre packs and enquire about supply."};
await build({base});
await build({base,build:{ssr:'src/main.jsx',outDir:'output/ssr',emptyOutDir:true}});
const {App}=await import(pathToFileURL(path.resolve('output/ssr/main.js')));
const template=await fs.readFile('dist/index.html','utf8');
const schema=o=>`<script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org',...o}).replaceAll('<','\\u003c')}</script>`;
function head(title,desc,url,image=site+'images/eylin-water-splash.webp'){
 return `<title>${esc(title)}</title><meta name="description" content="${esc(desc)}"><link rel="canonical" href="${url}"><meta name="robots" content="index,follow,max-image-preview:large"><meta property="og:type" content="website"><meta property="og:site_name" content="Nidhi Cosmetics"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(desc)}"><meta property="og:url" content="${url}"><meta property="og:image" content="${image}"><meta property="og:image:alt" content="${esc(title)}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(desc)}"><meta name="twitter:image" content="${image}">`;
}
function shell(meta,content,json){return template.replace(/<link rel="preload" as="image"[^>]*>/g,'').replace(/<title>[\s\S]*?<\/title>/,'').replace(/<meta name="description"[^>]*\/>/,'').replace('</head>',meta+json+'</head>').replace(/<script type="module"[^>]*><\/script>/g,'').replace('<div id="root"></div>',content)}
const org={'@type':'Organization','@id':site+'#organization',name:'Nidhi Cosmetics Pvt. Ltd.',url:site,logo:site+'images/nidhi-logo-original.png',email:'nidhicosmetics@gmail.com',telephone:'+91 93773 45680',address:{'@type':'PostalAddress',addressLocality:'Ahmedabad',addressCountry:'IN'}};
let home=template.replace(/<title>[\s\S]*?<\/title>/,'').replace(/<meta name="description"[^>]*\/>/,'').replace('</head>',head('Nidhi Cosmetics | EYLIN Bath, Body & Hotel Amenities','Explore EYLIN bath and body collections, guest amenities, handwash and housekeeping products from Nidhi Cosmetics in Ahmedabad. Enquire for samples and custom packaging.',site)+schema(org)+schema({'@type':'WebSite','@id':site+'#website',url:site,name:'Nidhi Cosmetics',publisher:{'@id':site+'#organization'}})+'</head>').replace('<div id="root"></div>',`<div id="root">${renderToString(React.createElement(App))}</div>`);
await fs.writeFile('dist/index.html',home);
const nav=`<header class="seo-header"><a href="${base}" aria-label="Nidhi Cosmetics home"><img src="${base}images/nidhi-logo-original.png" width="206" height="65" alt="Nidhi Cosmetics"></a><a href="${base}catalogue/">All products</a><a href="${base}#contact">Contact us</a></header><form class="seo-search" role="search" action="${base}" method="get"><label for="site-search">Search the catalogue</label><input id="site-search" name="q" type="search" placeholder="Product, collection or ingredient" required><button type="submit">Search</button></form>`;
const css=`<style>.seo-search{max-width:1280px;padding:18px 6% 0;margin:auto;display:flex;align-items:center;gap:12px;font-size:12px}.seo-search input{flex:1;min-width:0;min-height:44px;padding:10px;border:1px solid var(--border);background:var(--bg);color:var(--text);font:inherit}.seo-search button{min-height:44px;padding:10px 20px;background:var(--accent);color:var(--button-text)}@media(max-width:767px){.seo-search{flex-wrap:wrap}.seo-search label{width:100%}.seo-search input{font-size:16px}}.seo-header{height:auto;min-height:95px;display:flex;gap:28px;justify-content:space-between;padding:20px 6%;border-bottom:1px solid var(--border)}.seo-header img{width:180px;height:auto}.seo-header a{font-size:12px}.seo-main{max-width:1280px;margin:auto;padding:40px 6% 80px}.seo-main h1{font:clamp(30px,4vw,52px)/1.15 Poppins,sans-serif;margin:24px 0}.seo-main p{line-height:1.8;color:var(--muted);font-size:14px}.seo-detail{display:grid;grid-template-columns:1fr 1fr;gap:50px;margin-top:32px}.seo-detail>img{width:100%;height:550px;object-fit:contain;background:var(--panel)}.seo-detail .button{margin-top:25px}.seo-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:30px;margin:30px 0}.seo-grid img{aspect-ratio:1;object-fit:contain;background:var(--panel)}.seo-grid h2{font:17px/1.5 Poppins,sans-serif;margin:15px 0 6px}.seo-categories{display:flex;gap:12px 24px;flex-wrap:wrap;padding:24px 0;border-bottom:1px solid var(--border);font-size:13px}.seo-gallery{display:grid;grid-template-columns:repeat(3,1fr);gap:20px;margin-top:35px}.seo-gallery img{aspect-ratio:1;object-fit:contain}.seo-breadcrumb{font-size:12px;color:var(--muted);line-height:1.8}.seo-footer{padding:30px 6%;font-size:12px}@media(max-width:767px){.seo-detail{grid-template-columns:1fr;gap:24px}.seo-detail>img{height:350px}.seo-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:24px 16px}.seo-header{gap:18px;flex-wrap:wrap}.seo-header img{width:145px}.seo-gallery{grid-template-columns:1fr 1fr}}</style>`;
const footer=`<footer class="seo-footer">Nidhi Cosmetics · Ahmedabad, India · <a href="mailto:nidhicosmetics@gmail.com">nidhicosmetics@gmail.com</a></footer>`;
const urls=[site];
async function write(route,html){await fs.mkdir('dist/'+route,{recursive:true});await fs.writeFile('dist/'+route+'/index.html',html);urls.push(site+route+'/')}
const card=p=>`<article><a href="${base}products/${p.id}/"><img src="${base}images/${p.image}-480.webp" alt="${esc(p.name)}" width="480" height="480" loading="lazy"><h2>${esc(p.name)}</h2></a><p>${esc(p.detail)}</p></article>`;
for(const category of [null,...categories]){const list=category?products.filter(p=>p.category===category):products;const route=category?'categories/'+slug(category):'catalogue';const title=category||'Complete Product Catalogue';const desc=category?categoryCopy[category]:'Browse all 126 Nidhi Cosmetics products across bath and body care, guest amenities and housekeeping ranges.';const content=nav+`<main class="seo-main"><nav class="seo-breadcrumb"><a href="${base}">Home</a> / ${esc(title)}</nav><h1>${esc(title)}</h1><p>${esc(desc)}</p><nav class="seo-categories" aria-label="Product categories">${categories.map(c=>`<a href="${base}categories/${slug(c)}/">${esc(c)}</a>`).join('')}</nav><div class="seo-grid">${list.map(card).join('')}</div></main>`+footer;await write(route,shell(head(title+' | Nidhi Cosmetics',desc,site+route+'/')+css,content,schema({'@type':'CollectionPage',name:title,url:site+route+'/',description:desc,isPartOf:{'@id':site+'#website'},mainEntity:{'@type':'ItemList',numberOfItems:list.length,itemListElement:list.map((p,i)=>({'@type':'ListItem',position:i+1,url:site+'products/'+p.id+'/'}))}})+schema({'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:site},{'@type':'ListItem',position:2,name:title,item:site+route+'/'}]})))}
for(const p of products){const url=site+'products/'+p.id+'/';const desc=`${p.name}. ${p.detail}. Enquire with Nidhi Cosmetics for sizes, packaging, samples and order quantities.`;const crumbs=[['Home',site],[p.category,site+'categories/'+slug(p.category)+'/'],[p.name,url]];const content=nav+`<main class="seo-main"><nav class="seo-breadcrumb" aria-label="Breadcrumb"><a href="${base}">Home</a> / <a href="${base}categories/${slug(p.category)}/">${esc(p.category)}</a> / ${esc(p.name)}</nav><div class="seo-detail"><img src="${base}images/${p.image}-800.webp" alt="${esc(p.name)}" width="800" height="800" fetchpriority="high"><div><p>${esc(p.collection)}</p><h1>${esc(p.name)}</h1><p>${esc(p.description)}</p><p>${esc(p.detail)}</p>${p.imageNote?'<p>'+esc(p.imageNote)+'</p>':''}<a class="button primary" href="${base}?product=${p.id}#collection">Request a sample</a><p>Availability, pack sizes, kit contents and pricing are confirmed on enquiry.</p></div></div><div class="seo-gallery">${p.gallery.slice(1).map(im=>`<img src="${base}images/${im}-800.webp" alt="${esc(p.name)} alternate photograph" width="800" height="800" loading="lazy">`).join('')}</div><h2 style="margin-top:50px">More from this collection</h2><div class="seo-grid">${products.filter(o=>o.collection===p.collection&&o.id!==p.id).slice(0,3).map(card).join('')}</div></main>`+footer;await write('products/'+p.id,shell(head(p.name+' | Nidhi Cosmetics',desc,url,site+'images/'+p.image+'.webp')+css,content,schema({'@type':'Product',name:p.name,description:desc,image:p.gallery.map(i=>site+'images/'+i+'.webp'),category:p.category,mainEntityOfPage:{'@type':'WebPage','@id':url},manufacturer:{'@id':site+'#organization'},brand:{'@type':'Brand',name:p.line},url})+schema({'@type':'BreadcrumbList',itemListElement:crumbs.map(([name,item],i)=>({'@type':'ListItem',position:i+1,name,item}))})))}
await fs.writeFile('dist/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">${urls.map(url=>{const p=products.find(p=>url===site+'products/'+p.id+'/');return `<url><loc>${url}</loc>${p?`<image:image><image:loc>${site}images/${p.image}.webp</image:loc></image:image>`:''}</url>`}).join('')}</urlset>`);
await fs.writeFile('dist/robots.txt',`User-agent: *\nAllow: /\nSitemap: ${site}sitemap.xml\n`);
console.log(`SEO build: ${urls.length} static pages with canonical metadata and sitemap.`);

await fs.writeFile('dist/404.html',shell(head('Page not found | Nidhi Cosmetics','This page could not be found.',site+'404.html').replace('index,follow,max-image-preview:large','noindex,follow')+css,nav+'<main class="seo-main"><h1>Page not found.</h1><p>Explore the catalogue or use search to find your product.</p><a class="button primary" href="'+base+'catalogue/">Browse all products</a></main>'+footer,''));
