import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight,ArrowRight,MagnifyingGlass,Handbag,X,Plus,Minus,List,Leaf,Package,GlobeHemisphereWest,Check,Sun,Moon} from '@phosphor-icons/react';
import '@fontsource/manrope/latin-400.css';
import '@fontsource/manrope/latin-500.css';
import '@fontsource/manrope/latin-600.css';
import '@fontsource/cormorant-garamond/latin-400.css';
import '@fontsource/cormorant-garamond/latin-400-italic.css';
import './style.css';
import './premium.css';
import './splash.css';
import './storefront.css';
import './catalogue.css';
import products from './data/products.json';
import categoryNames from './data/categories.json';
import {filterProducts,matchesSearch} from './catalogue.mjs';
import '@fontsource/jost/latin-400.css';
import '@fontsource/jost/latin-500.css';
import '@fontsource/poppins/latin-400.css';
import '@fontsource/poppins/latin-500.css';
const img=n=>`${import.meta.env.BASE_URL}images/${typeof n==='number'?`eylin-${n}`:n}.webp`;
const categories=['All products',...categoryNames];
const collections=['All collections',...new Set(products.map(p=>p.collection))];
function Photo({src,fetchPriority,...props}){return <img {...props} src={src} srcSet={src.replace('.webp','-480.webp')+' 480w, '+src.replace('.webp','-800.webp')+' 800w, '+src+' 1600w'} sizes={fetchPriority?'100vw':'(max-width: 767px) 90vw, 50vw'} fetchPriority={fetchPriority}/>}
function App(){
const [campaignPaused,setCampaignPaused]=useState(false);
const [collection,setCollection]=useState('All collections'),[sort,setSort]=useState('featured'),[limit,setLimit]=useState(24);
const [filter,setFilter]=useState('All products'),[search,setSearch]=useState(''),[searchOpen,setSearchOpen]=useState(false),[menu,setMenu]=useState(false),[detail,setDetail]=useState(null),[gallery,setGallery]=useState(0),[bagOpen,setBagOpen]=useState(false),[enquiry,setEnquiry]=useState(false),[prepared,setPrepared]=useState(''),[toast,setToast]=useState('');
const [bag,setBag]=useState(()=>{try{return JSON.parse(localStorage.getItem('nidhi-shortlist')||'[]').map(x=>({...x,id:({'body-essentials':'botanical-set','spa-ritual':'spa-essentials'})[x.id]||x.id})).filter(x=>products.some(p=>p.id===x.id)&&Number.isInteger(x.qty)&&x.qty>0)}catch{return []}});
const [dark,setDark]=useState(()=>{try{const saved=localStorage.getItem('nidhi-theme');return saved?saved==='dark':matchMedia('(prefers-color-scheme: dark)').matches}catch{return false}});
useEffect(()=>{setLimit(24)},[filter,search,collection,sort]);
const dialog=useRef(null);const overlay=detail||bagOpen||enquiry||searchOpen;
useEffect(()=>{try{localStorage.setItem('nidhi-shortlist',JSON.stringify(bag))}catch{}},[bag]);
useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';try{localStorage.setItem('nidhi-theme',dark?'dark':'light')}catch{}},[dark]);
useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),3000);return()=>clearTimeout(t)},[toast]);
useEffect(()=>{if(overlay&&!dialog.current.open)dialog.current.showModal();else if(!overlay&&dialog.current.open)dialog.current.close()},[overlay]);
const close=()=>{setDetail(null);setBagOpen(false);setEnquiry(false);setSearchOpen(false);setPrepared('')};
const add=p=>{setBag(b=>b.some(x=>x.id===p.id)?b.map(x=>x.id===p.id?{...x,qty:x.qty+1}:x):[...b,{id:p.id,qty:1}]);setToast(`${p.name} added to your sample list`)};
const show=p=>{close();setGallery(0);setDetail(p)};
const go=c=>{setFilter(c);setSearch('');setCollection('All collections');setLimit(24);setMenu(false);close();location.hash='collection';document.getElementById('collection').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})};
const request=()=>{close();setEnquiry(true)};
const visible=filterProducts(products,{category:filter,collection,query:search,sort});
const resetCatalogue=()=>{setFilter('All products');setCollection('All collections');setSearch('');setSort('featured');};
function prepare(e){e.preventDefault();const f=new FormData(e.currentTarget);setPrepared(`Hello Nidhi Cosmetics,\n\nI'd like to enquire about ${f.get('interest')}.\n\nName: ${f.get('name')}\nEmail: ${f.get('email')}\nCompany: ${f.get('company')||'Not specified'}\n\nSample shortlist:\n${bag.length?bag.map(x=>`${products.find(p=>p.id===x.id).name} (requested quantity: ${x.qty})`).join('\n'):'Please recommend a collection.'}\n\n${f.get('message')}\n\nPlease share availability, specifications, minimum order quantities and a quotation.`)}
return <><a className="skip" href="#main">Skip to content</a><div className="announcement">Thoughtfully crafted in India. Made for moments of care.<span>EST. 2004</span></div>
<header><a href="#" className="brand" aria-label="Nidhi Cosmetics home"><img src={`${import.meta.env.BASE_URL}images/nidhi-logo-original.png`} alt="Nidhi Cosmetics" width="206" height="65"/></a><form className="store-search" role="search" onSubmit={e=>{e.preventDefault();const term=new FormData(e.currentTarget).get("query");go("All products");setSearch(term)}}><MagnifyingGlass/><input name="query" aria-label="Search the Nidhi collections" placeholder="Search for soaps, body care, gift sets..."/><button type="submit">SEARCH</button></form><nav aria-label="Main navigation"><a href="#collection" onClick={resetCatalogue}>Our collections</a><a href="#hospitality">For hospitality</a><a href="#story">Our story</a></nav><div className="header-actions"><button aria-label="Search products" onClick={()=>setSearchOpen(true)}><MagnifyingGlass/></button><button className="bag-button" aria-label={`Sample bag, ${bag.length} products`} onClick={()=>setBagOpen(true)}><Handbag/><span>{bag.length}</span></button><button className="header-enquire" onClick={request}>Enquire with us <ArrowUpRight/></button><button className="menu-toggle" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}><List/></button></div></header><nav className="store-nav" aria-label="Product categories">{categories.map(c=><button key={c} onClick={()=>go(c)}>{c}</button>)}<a href="#hospitality">For hospitality</a><a href="#story">Our story</a></nav>
{menu&&<nav className="mobile-nav"><a onClick={()=>setMenu(false)} href="#collection">Our collections</a><a onClick={()=>setMenu(false)} href="#hospitality">For hospitality</a><a onClick={()=>setMenu(false)} href="#story">Our story</a><button onClick={()=>{setMenu(false);request()}}>Enquire with us</button></nav>}
<main id="main"><section className="hero"><div className="hero-copy"><p className="eyebrow">EYLIN BOTANICAL BODY CARE</p><h1>MAKE A SPLASH. <br/><em>FEEL THE FRESH.</em></h1><p>Botanical bath and body essentials. Beautifully made for your skin, your senses, and your everyday.</p><a className="button primary" href="#collection">EXPLORE THE COLLECTION <ArrowUpRight size={18}/></a></div><div className="hero-art"><div className={`hero-image splash-campaign ${campaignPaused?"is-paused":""}`}><Photo src={`${import.meta.env.BASE_URL}images/eylin-water-splash.webp`} alt="EYLIN botanical shower gel surrounded by a water splash on sunlit wet stone" fetchPriority="high"/><button className="campaign-motion" onClick={()=>setCampaignPaused(!campaignPaused)} aria-pressed={campaignPaused} aria-label={campaignPaused?"Play motion":"Pause motion"}>{campaignPaused?"Play motion":"Pause motion"}</button></div><div className="hero-art-caption"><span>THE BOTANICAL RITUAL</span><span>A fresh moment of care.</span></div></div></section>
<section className="category-showcase" aria-label="Browse by category"><h2>SHOP BY CATEGORY</h2><div className="category-shortcuts">{categoryNames.map(c=><button key={c} onClick={()=>go(c)}><Photo src={img(products.find(p=>p.category===c).image)} alt="" loading="lazy"/><span>{c}</span></button>)}</div></section><div className="values"><span><Leaf/> Thoughtfully crafted</span><span><Package/> Bespoke hospitality amenities</span><span><GlobeHemisphereWest/> Made in India, for the world</span></div>
<section className="collection section" id="collection"><div className="section-heading"><h2>EXPLORE THE FULL CATALOGUE</h2><p className="catalogue-intro">Bath and body care, coordinated guest amenities and housekeeping essentials. Find the right products for every part of your property.</p></div><div className="catalogue-controls"><label>Find a product<input aria-label="Search catalogue" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Try moringa, shampoo, slippers..."/></label><label>Collection<select value={collection} onChange={e=>setCollection(e.target.value)}>{collections.map(c=><option key={c}>{c}</option>)}</select></label><label>Sort by<select value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Featured</option><option value="az">Name: A to Z</option><option value="za">Name: Z to A</option></select></label></div><div className="collection-tools"><div className="filters" aria-label="Filter collections">{categories.map(c=><button key={c} className={filter===c?'active':''} aria-pressed={filter===c} onClick={()=>setFilter(c)}>{c}<small>{filterProducts(products,{category:c,collection,query:search}).length}</small></button>)}</div><span className="result-count">{visible.length} products</span></div><div className="catalogue-status" aria-live="polite"><span>{filter==='All products'?'All categories':filter}{collection!=='All collections'?' / '+collection:''}{search?' / “'+search+'”':''}</span>{(search||filter!=='All products'||collection!=='All collections')&&<button onClick={resetCatalogue}>Clear filters</button>}</div><div className="product-grid">{visible.slice(0,limit).map(p=><article className="product" data-collection={p.line} key={p.id}><button className="product-photo" onClick={()=>show(p)} aria-label={`Explore ${p.name}`}><Photo src={img(p.image)} loading="lazy" alt={p.name}/><span className="photo-action">Discover <ArrowUpRight/></span></button><div className="product-info"><p>{p.collection}</p><div><button className="product-name" onClick={()=>show(p)}>{p.name}</button><button className="add-button" aria-label={`Add ${p.name} to sample list`} onClick={()=>add(p)}><Plus/></button></div><span>{p.detail}</span><button className="product-sample" aria-label={`Add to sample bag: ${p.name}`} onClick={()=>add(p)}>ADD TO SAMPLE BAG <Plus size={14}/></button></div></article>)}</div>{!visible.length&&<div className="empty"><h3>No products found.</h3><p>Try another product name or clear your filters.</p><button className="button" onClick={resetCatalogue}>View all products</button></div>}{visible.length>0&&<div className="catalogue-more"><span>Showing {Math.min(limit,visible.length)} of {visible.length} products</span>{limit<visible.length&&<button className="button primary" onClick={()=>setLimit(n=>n+24)}>Load more products <Plus/></button>}</div>}</section>
<section className="collection-worlds section" aria-label="Discover our collections"><div className="world-heading"><p>Discover our bath and body collections.</p><h2>Find your <em>kind of care.</em></h2></div><button className="collection-world botanical-world" onClick={()=>{go("All products");setCollection("EYLIN Fuji Green Tea")}}><div className="world-copy"><span>EYLIN BOTANICAL</span><h3>Nature, in<br/>your daily ritual.</h3><p>Delicate botanicals. A fresh perspective on everyday care.</p><span className="world-link">Explore botanical <ArrowUpRight/></span></div><Photo src={img(6)} alt="Botanical soap with green tea and flowers" loading="lazy"/></button><button className="collection-world spa-world" onClick={()=>{go("All products");setCollection("EYLIN Spa Absolute Jasmin")}}><div className="world-copy"><span>EYLIN SPA</span><h3>Your own<br/>little escape.</h3><p>A considered collection for slow mornings and softer landings.</p><span className="world-link">Enter the spa <ArrowUpRight/></span></div><Photo src={img(9)} alt="EYLIN Spa Absolute Jasmin collection" loading="lazy"/></button></section>
<section className="hospitality section" id="hospitality"><div><p className="eyebrow">THE DETAILS MAKE THE STAY</p><h2>A warm welcome,<br/><em>beautifully bottled.</em></h2><p>From boutique retreats to distinctive hotels, create a guest experience that feels like you. Explore our collections and customised amenities.</p><button className="button primary" onClick={request}>Create your guest experience <ArrowUpRight/></button></div><Photo src={img(11)} alt="EYLIN Spa amenities and gift presentation" loading="lazy"/></section>
<section className="story section" id="story"><div className="story-year"><span>OUR ROOTS</span>Made with care.<br/><em>Since 2004.</em></div><div><h2>Care is in our nature.</h2><p>Based in Ahmedabad, Nidhi Cosmetics brings together bath, body and hospitality essentials with a thoughtful approach to manufacturing. We work with businesses to create products and presentations that make every welcome feel personal.</p><a className="text-link" href="mailto:nidhicosmetics@gmail.com">Let's make something beautiful <ArrowUpRight/></a></div></section>
<section className="faq section"><h2>A little more to know.</h2><div>{[['Can we customise products for our hotel?','Yes. Nidhi Cosmetics handles customised hospitality requirements. Share your brand, product preferences and quantities so our team can discuss packaging and available options.'],['How do I request samples or pricing?','Add products to your sample list, then prepare an enquiry. Your email app opens with your selections ready to send. Our team will confirm sample availability, pricing and order quantities.'],['Do you supply other hotel amenities?','Our range also includes bathroom and in-room amenities, from dental and shaving kits to slippers and guest-room essentials. Tell us what your property needs.']].map(([q,a])=><details key={q}><summary>{q}<Plus/></summary><p>{a}</p></details>)}</div></section></main>
<footer id="contact"><div className="footer-top"><a href="#" className="brand"><img src={`${import.meta.env.BASE_URL}images/nidhi-logo-original.png`} alt="Nidhi Cosmetics" width="206" height="65"/></a><p>Everyday essentials.<br/>Exceptionally considered.</p><div><h3>Explore</h3><a href="#collection">Our collections</a><a href="#hospitality">For hospitality</a><a href="#story">Our story</a></div><div><h3>Let's talk</h3><a href="mailto:nidhicosmetics@gmail.com">nidhicosmetics@gmail.com</a><a href="tel:+919377345680">+91 93773 45680</a><span>Ahmedabad, India</span></div></div><div className="footer-signature" aria-hidden="true">beautiful, by nature.</div><div className="footer-bottom"><span>© {new Date().getFullYear()} Nidhi Cosmetics Pvt. Ltd.</span><span>Crafted with care. Since 2004.</span><button onClick={()=>setDark(!dark)} aria-label={`Switch to ${dark?'Light':'Dark'} appearance`}>{dark?<Sun/>:<Moon/>} {dark?'Light':'Dark'} appearance</button></div></footer>
<dialog ref={dialog} aria-label={detail?detail.name:bagOpen?'Sample list':searchOpen?'Product search':'Enquiry'} onCancel={close} onClick={e=>{if(e.target===dialog.current)close()}}><div className={`dialog-content ${detail?'detail-dialog':''}`}><button className="close" aria-label="Close dialog" onClick={close}><X/></button>
{searchOpen&&<><h2>Find your ritual.</h2><label htmlFor="search">Search the collections</label><div className="search-field"><MagnifyingGlass/><input id="search" autoFocus placeholder="Try botanical, soap or spa" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="search-results">{products.filter(p=>matchesSearch(p,search)).map(p=><button key={p.id} onClick={()=>show(p)}><Photo src={img(p.image)} alt=""/><span>{p.name}<small>{p.line}</small></span><ArrowUpRight/></button>)}{!products.some(p=>matchesSearch(p,search))&&<p>No matches. Try “soap” or “spa”.</p>}</div></>}
{detail&&<><div><Photo className="detail-image" src={img(detail.gallery[gallery])} alt={detail.name}/><div className="thumbnails">{detail.gallery.map((n,i)=><button aria-label={`View photo ${i+1}`} aria-pressed={gallery===i} onClick={()=>setGallery(i)} key={n}><Photo src={img(n)} alt=""/></button>)}</div></div><div className="detail-copy"><p className="eyebrow">{detail.collection}</p><p className="product-category-label">{detail.category}</p><h2>{detail.name}</h2><p>{detail.description}</p><p className="detail-note">{detail.detail}</p>{detail.imageNote&&<p className="image-note">{detail.imageNote}</p>}<button className="button primary" onClick={()=>add(detail)}>Add to sample list <Plus/></button><button className="text-link" onClick={()=>{close();setBagOpen(true)}}>View sample list <ArrowRight/></button><p className="small">Availability, pack sizes, kit contents and pricing are confirmed on enquiry.</p></div></>}
{bagOpen&&<><p className="eyebrow">YOUR SELECTION</p><h2>A little list of care.</h2>{!bag.length?<div className="empty"><Handbag size={36}/><p>Your sample list is waiting to be filled.</p><button className="button primary" onClick={()=>go('All products')}>Explore the essentials <ArrowRight/></button></div>:<><div className="bag-items">{bag.map(x=>{const p=products.find(p=>p.id===x.id);return <div className="bag-item" key={x.id}><Photo src={img(p.image)} alt={p.name}/><div><h3>{p.name}</h3><small>Requested sample quantity</small><div className="quantity"><button aria-label={`Decrease ${p.name}`} onClick={()=>setBag(b=>b.map(i=>i.id===x.id?{...i,qty:Math.max(1,i.qty-1)}:i))}><Minus/></button><span>{x.qty}</span><button aria-label={`Increase ${p.name}`} onClick={()=>setBag(b=>b.map(i=>i.id===x.id?{...i,qty:i.qty+1}:i))}><Plus/></button><button className="remove" onClick={()=>setBag(b=>b.filter(i=>i.id!==x.id))}>Remove</button></div></div></div>})}</div><p className="small">This is an enquiry list. Sample availability and any charges will be confirmed by our team.</p><button className="button primary" onClick={request}>Enquire about my selection <ArrowUpRight/></button></>}</>}
{enquiry&&<><p className="eyebrow">LET'S CREATE SOMETHING CONSIDERED</p><h2>Your next chapter of care.</h2>{prepared?<div className="prepared"><Check size={30}/><h3>Your enquiry is ready.</h3><p>Open your email app to review and send it to Nidhi Cosmetics. Nothing has been sent yet.</p><a className="button primary" href={`mailto:nidhicosmetics@gmail.com?subject=${encodeURIComponent('Collection and sample enquiry')}&body=${encodeURIComponent(prepared)}`}>Open email to send <ArrowUpRight/></a><button className="text-link" onClick={()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([prepared],{type:'text/plain'}));a.download='nidhi-enquiry.txt';a.click();URL.revokeObjectURL(a.href)}}>Download enquiry instead</button><pre>{prepared}</pre></div>:<form onSubmit={prepare}><p>Tell us a little about what you have in mind.</p><div className="form-grid"><label>Your name<input name="name" autoComplete="name" required placeholder="Full name"/></label><label>Email address<input name="email" autoComplete="email" type="email" required placeholder="you@company.com"/></label></div><label>Hotel or company <span>(optional)</span><input name="company" autoComplete="organization" placeholder="Your company"/></label><label>I'm interested in<select name="interest"><option>Samples and product pricing</option><option>Customised hotel amenities</option><option>Bath and body collections</option><option>Dry guest amenities and slippers</option><option>Handwash and dispensers</option><option>Cleaning products and air fresheners</option><option>Other hotel amenities</option></select></label><label>A few details<textarea name="message" rows="3" placeholder="Products, quantities, packaging ideas or your project timeline"/></label><p className="small">This prepares an email on your device. Your details are not stored by this website.</p><button className="button primary" type="submit">Prepare my enquiry <ArrowUpRight/></button></form>}</>}
</div></dialog>{toast&&<div className="toast" role="status"><Check/>{toast}</div>}</>
}
createRoot(document.getElementById('root')).render(<App/>);


