import React,{useId,useState} from 'react';
import {MagnifyingGlass,ArrowUpRight,X} from '@phosphor-icons/react';
import {filterProducts} from './catalogue.mjs';
import './search.css';
export default function ProductSearch({products,onSearch,onSelect,expanded=false}){
 const id=useId(),[query,setQuery]=useState(''),[open,setOpen]=useState(expanded),[selected,setSelected]=useState(-1);
 const results=query.trim()?filterProducts(products,{query}):[];const top=results.slice(0,6);const showing=open&&query.trim().length>0;
 function submit(e){e.preventDefault();if(selected>=0&&top[selected])onSelect(top[selected]);else onSearch(query.trim());setOpen(false);setSelected(-1)}
 return <div className={`product-search ${expanded?'expanded-search':'header-product-search'}`} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget)&&!expanded)setOpen(false)}}>
 <form className="store-search" role="search" onSubmit={submit}><MagnifyingGlass aria-hidden="true"/><input value={query} name="q" role="combobox" aria-label="Search products and collections" aria-autocomplete="list" aria-expanded={!!showing} aria-controls={id} aria-activedescendant={showing&&selected>=0?`${id}-${selected}`:undefined} placeholder="Search products, ingredients or collections" autoComplete="off" autoFocus={expanded} onFocus={()=>setOpen(true)} onChange={e=>{setQuery(e.target.value);setSelected(-1);setOpen(true)}} onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);setSelected(-1);e.stopPropagation()}if(e.key==='ArrowDown'&&top.length){e.preventDefault();setOpen(true);setSelected(n=>(n+1)%top.length)}if(e.key==='ArrowUp'&&top.length){e.preventDefault();setSelected(n=>(n<=0?top.length:n)-1)}}}/>{query&&<button type="button" className="search-clear" aria-label="Clear search" onClick={()=>{setQuery('');setSelected(-1);setOpen(true)}}><X size={16}/></button>}<button type="submit">Search</button></form>
 {!showing&&<div id={id} role="listbox" aria-label="Suggested products" hidden/>}{showing&&<div className="search-suggestions"><p className="search-summary" role="status">{results.length?`${results.length} matching products`:'No matching products'}</p><div id={id} role="listbox" aria-label="Suggested products">{top.map((p,i)=><button type="button" key={p.id} id={`${id}-${i}`} role="option" aria-selected={selected===i} onMouseDown={e=>e.preventDefault()} onClick={()=>{onSelect(p);setOpen(false)}}><img src={`${import.meta.env.BASE_URL}images/${p.image}-480.webp`} alt="" width="52" height="58"/><span>{p.name}<small>{p.category} · {p.collection}</small></span><ArrowUpRight aria-hidden="true"/></button>)}</div>{results.length>0?<button className="search-view-all" onClick={()=>{onSearch(query.trim());setOpen(false)}}>View all {results.length} results <ArrowUpRight/></button>:<p className="search-advice">Try a product type such as shampoo, handwash or slippers, or a collection such as Moringa.</p>}</div>}
 {expanded&&!query&&<div className="popular-searches"><p>Popular searches</p>{['Shampoo','Hand wash','Moringa','Body wash','Slippers','Dental kit'].map(term=><button key={term} onClick={()=>{setQuery(term);setOpen(true)}}>{term}</button>)}</div>}
 </div>
}
